onEvent('block.registry', event => {
    event.create('geode')
        .material('iron')
        .hardness(3)
        .displayName('Geode')
        .harvestTool('pickaxe', 2)
        .waterlogged()
        .requiresTool(true)
        .texture('kubejs:block/geode.png')
        .renderType('cutout')
        .fullBlock(false)
        .box(4, 0, 4, 12, 11, 12, true)
        .item(itemBuilder => {
            itemBuilder.maxStackSize(16)
            itemBuilder.tooltip([Text.translate('plus.blocks.geode.tooltip')])
            itemBuilder.texture('kubejs:item/geode.png')
            itemBuilder.group('decorations')
        })

    event.create('cracked_geode')
        .material('iron')
        .hardness(3)
        .displayName('Cracked Geode')
        .harvestTool('pickaxe', 2)
        .waterlogged()
        .requiresTool(true)
        .texture('kubejs:block/cracked_geode.png')
        .renderType('cutout')
        .fullBlock(false)
        .box(4, 0, 4, 12, 11, 12, true)
        .item(itemBuilder => {
            itemBuilder.maxStackSize(16)
            itemBuilder.tooltip([Text.translate('plus.blocks.cracked_geode.tooltip')])
            itemBuilder.texture('kubejs:item/cracked_geode.png')
            itemBuilder.group('decorations')
        })

    event.create('geode_ore')
        .material('rock')
        .hardness(3)
        .displayName('Geode Ore')
        .harvestTool('pickaxe', 2)
        .requiresTool(true)
        .item(itemBuilder => {
            itemBuilder.group('building_blocks')
        })
})